### ISSUE TITLE
Error:

### ISSUE THREAD

**Issue by WaltDisneyWorld** [jluims/RobloxGen#1]
```TypeError: Cannot read properties of null (reading '1')
    at Function.createAccount (C:\Users\ZOOM\Downloads\RobloxGen-main\RobloxGen-main\RobloxUtils.js:95:43)
    at processTicksAndRejections (node:internal/process/task_queues:96:5)
    at async C:\Users\ZOOM\Downloads\RobloxGen-main\RobloxGen-main\index.js:17:21```

**Comment by jose-lms** [comment]
Never thought anyone would want to use this lol. Could you post the full error? (It's been patched by ROBLOX a while ago but I'll try to get it up and running again when I have time)

**Comment by jose-lms** [comment]
Nevermind, no need for the error. I'll reverse engineer the sign up system when I have time!

**Comment by WaltDisneyWorld** [comment]
It’s an awesome system.

**Comment by jose-lms** [comment]
@WaltDisneyWorld It's been updated! Finally found a way to fix this after they updated the sign up system a few months ago. If you run into any more issues, make sure to tell me! 😊

**Comment by WaltDisneyWorld** [comment]
Thanks soooo muchhh!!!
