### ISSUE TITLE
feature request: improve account generation

### ISSUE THREAD

**Issue by nh084817** [jluims/RobloxGen#14]
hi, great system, but id like to point out some things about the account generation function.

currently, the generator does not have a randomizer for `birthday`, `gender` and `user-agent`.
the birthday is set to exactly `07 Sep 1942`,
the gender as `male` and the user-agent as `Chrome/95.0`

now im no expert but, wouldn't ROBLOX be wary of multiple players having the same birthday and user-agent and the fact that they are being created continuously?

i believe a randomizer will reduce the suspicion of the accounts, and the repetitiveness of em

**Comment by KC080** [comment]
tbh, i dont think the birthday part matters since it doesnt really affect suspicion (from what i know) but useragents are definitely one of the things which would arise suspicion also ip addresses

**Comment by WaltDisneyWorld** [comment]
Yeah.

**Comment by jluims** [comment]
Yeah I'll definitely work on this. At first this project was just a quick and buggy mess that wasn't supposed to be public lol.

**Comment by Arcxdd** [comment]
Birthday, gender, and user agent randomizer all added.
