### ISSUE TITLE
Failed to get field data

### ISSUE THREAD

**Issue by KC080** [jluims/RobloxGen#18]
doing the captcha will say failed to get field data even after restarting multiple times.

**Comment by jluims** [comment]
Maybe you're being rate-limited. Did you do ~30 captchas or more before getting the error?

**Comment by KC080** [comment]
> Maybe you're being rate-limited. Did you do ~30 captchas or more before getting the error?

yeah, what do you think can prevent ratelimitation?

**Comment by Zgross1** [comment]
Use something like ExpressVPN.

**Comment by jluims** [comment]
proxy support will be added eventually
