### ISSUE TITLE
Could this be useful in future development?

### ISSUE THREAD

**Issue by z9841** [jluims/RobloxGen#26]
Hello,
I have recently came across this repo which claims to be able to interface Roblox FunCaptchas.
Here is the link:
https://github.com/noahcoolboy/roblox-funcaptcha

**Comment by jluims** [comment]
While it does look cool, I'm not sure what it can be used for in terms of this project

**Comment by Arcxdd** [comment]
If we want to make our own gui to solve the captcha or auto-solve the captcha with some AI, then sure. But now, this is not needed.
