### ISSUE TITLE
Failed to connect to the database

### ISSUE THREAD

**Issue by KC080** [jluims/RobloxGen#6]
[❌] Failed to connect to the database (Error: connect ECONNREFUSED 127.0.0.1:3306)

**Comment by jluims** [comment]
Do you have a MySQL database set up?

**Comment by KC080** [comment]
> Do you have a MySQL database set up?

Sorry if I sound stupid, but how do I set up one?

**Comment by Arcxdd** [comment]
You have to set up a MySQL database yourself.

You can google how to create one, or use an online service for it.

**Comment by WaltDisneyWorld** [comment]
I recommend using a service like clever-cloud. You can create unlimited free mongo,SQL, redis and other servers for free!
https://clever-cloud.com
