### ISSUE TITLE
Restructuring Account creation

### ISSUE THREAD

**Issue by WaltDisneyWorld** [jluims/RobloxGen#8]
I’m going to restructure the way accounts are generated, and change the username format to make them more realistic.

**Comment by jluims** [comment]
account creation is working as of yesterday. btw gotta review a pr first

**Comment by Arcxdd** [comment]
ehm

**Comment by WaltDisneyWorld** [comment]
Noo I’m doing that

**Comment by WaltDisneyWorld** [comment]
The username system.

**Comment by jluims** [comment]
> The username system.

Go for it, leave a PR and i'll review it

**Comment by Arcxdd** [comment]
I'll push it to my fork and create a pr, that way you can decide which one is better. I'm going to try to look for a username generator API service, if that doesn't work then I'll write an algorithm to generate usernames.

**Comment by Arcxdd** [comment]
But I'm doing that tomorrow.

**Comment by jluims** [comment]
I'll keep whichever one is better overall

**Comment by Arcxdd** [comment]
Usernames look more legit now.
